name: Run Build and Tests

on:
  push:
    branches: [ main, ci-scratch ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-bin:

    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Prepare toolchain
      run: rustup show
    - uses: Swatinem/rust-cache@v1

    - name: Install OpenSSL (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
        vcpkg install openssl:x64-windows
        echo "OPENSSL_DIR=C:\vcpkg\installed\x64-windows" >> $env:GITHUB_ENV


    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
