name: Run Build for UWP

on:
  push:
    branches: [main, ci-scratch]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-uwp:
    runs-on: windows-latest
    env:
      VCPKGRS_TRIPLET: x64-uwp
      UWP_CROSS_TARGET_TRIPLET: x86_64-uwp-windows-msvc
      UWP_NATIVE_TARGET_TRIPLET: x86_64-uwp-windows-msvc
      BUILD_STD_ARGS: build-std=std,panic_abort
      # THUMBV7A_UWP_WINDOWS_MSVC_OPENSSL_DIR: 'C:\vcpkg\installed\arm-uwp'
      X86_64_UWP_WINDOWS_MSVC_OPENSSL_DIR: 'C:\vcpkg\installed\x64-uwp'

    steps:
      - uses: actions/checkout@v2
      - name: Prepare toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v1

      - name: Install OpenSSL
        run: vcpkg install openssl:x64-uwp

      - name: Build x64
        run: cargo build -p ytflow-app-util -Z $env:BUILD_STD_ARGS --target $env:UWP_CROSS_TARGET_TRIPLET --release
